//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetSadNet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetSad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetSad()
        {
            this.SadNets = new HashSet<SadNet>();
            //Создание списка из элементов
        }
    
        public int SadID { get; set; }
        //Идентификатор
        public string Name { get; set; }
        //Название сада
        public string City { get; set; }
        //Город
        public string Adress { get; set; }
        //Адрес
        public string People { get; set; }
        //Количесво детей
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SadNet> SadNets { get; set; }
    }
}
