//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetSadNet.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SadNetEntities : DbContext
    {
        public SadNetEntities()
            : base("name=SadNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetSad> DetSads { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<SadNet> SadNets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
