//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetSadNet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SadNet
    {
        public int SadID { get; set; }
        public int SadDirectorID { get; set; }
        public decimal PlataForMonth { get; set; }
        public System.DateTime DateOpen { get; set; }
        public int IdSad { get; set; }
    
        public virtual DetSad DetSad { get; set; }
        public virtual Director Director { get; set; }
    }
}
